name: AdventOfCode2021
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
          stable: 'true'

      - name: Check test coverage
        run: go test ./... -cover
